#!/usr/bin/env bash

if
  [[ -s "/home/ayu/.rvm/gems/ruby-2.7.4/environment" ]]
then
  source "/home/ayu/.rvm/gems/ruby-2.7.4/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ayu/.rvm/gems/ruby-2.7.4/environment'" >&2
  exit 1
fi
